config/accounts/urls.py
from accounts.views import SignUpView, SignInView, UserLogoutView
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('sign_up/', SignUpView.as_view(), name='sign_up'),
    path('sign_in/', SignInView.as_view(), name='sign_in'),
    path('logout/', UserLogoutView.as_view(), name='logout')

]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import TripListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TripListView.as_view(), name='trip_list'),
    path('core/', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

config/core/urls.py
from core.views import TripDetailsView, template_elements, \
    insurance, ContinentCreateView, CountryCreateView, CityCreateView, AirportCreateView, \
    HotelCreateView, TripCreateView, AdminListView, ContinentDeleteView, AdminContinentDetailView, ContinentUpdateView, \
    AdminTripDetailView, AdminCityDetailView, AdminAirportDetailView, AdminHotelDetailView, AdminCountryDetailView, \
    CountryUpdateView, CityUpdateView, TripUpdateView, AirportUpdateView, HotelUpdateView, CountryDeleteView, \
    HotelDeleteView, AirportDeleteView, TripDeleteView, CityDeleteView, HotelListView, AdditionalServicesView, \
    contact, TripPurchaseCreateView, SearchResultsView, TripPurchaseSummaryView
from django.urls import path
from django.views.decorators.http import require_POST

app_name = 'core'
urlpatterns = [
    path('hotels/', HotelListView.as_view(), name='hotels'),
    path('additional_services/', AdditionalServicesView.as_view(), name='additional_services'),
    path('search_results/', SearchResultsView.as_view(), name='search_results'),

    path('trip_details/<pk>/', TripDetailsView.as_view(), name='trip_details'),
    path('trip_purchase/<pk>/', TripPurchaseCreateView.as_view(), name='trip_purchase'),
    path('trip_purchase_summary/', TripPurchaseSummaryView.as_view(), name='trip_purchase_summary'),

    path('contact/', contact, name='contact'),
    path('elements/', template_elements, name='elements'),
    path('insurance/', insurance, name='insurance'),

    path('add_continent/', ContinentCreateView.as_view(), name='add_continent'),
    path('add_country/', CountryCreateView.as_view(), name='add_country'),
    path('add_city/', CityCreateView.as_view(), name='add_city'),
    path('add_hotel/', HotelCreateView.as_view(), name='add_hotel'),
    path('add_airport/', AirportCreateView.as_view(), name='add_airport'),
    path('add_trip/', TripCreateView.as_view(), name='add_trip'),

    path('admin_list/', AdminListView.as_view(), name='admin_list'),
    path('admin_continent_details/<pk>/', AdminContinentDetailView.as_view(), name='admin_continent_details'),
    path('admin_country_details/<pk>/', AdminCountryDetailView.as_view(), name='admin_country_details'),
    path('admin_city_details/<pk>/', AdminCityDetailView.as_view(), name='admin_city_details'),
    path('admin_hotel_details/<pk>/', AdminHotelDetailView.as_view(), name='admin_hotel_details'),
    path('admin_airport_details/<pk>/', AdminAirportDetailView.as_view(), name='admin_airport_details'),
    path('admin_trip_details/<pk>/', AdminTripDetailView.as_view(), name='admin_trip_details'),

    path('continent_update/<pk>/', ContinentUpdateView.as_view(), name='continent_update'),
    path('country_update/<pk>/', CountryUpdateView.as_view(), name='country_update'),
    path('city_update/<pk>/', CityUpdateView.as_view(), name='city_update'),
    path('hotel_update/<pk>/', HotelUpdateView.as_view(), name='hotel_update'),
    path('airport_update/<pk>/', AirportUpdateView.as_view(), name='airport_update'),
    path('trip_update/<pk>/', TripUpdateView.as_view(), name='trip_update'),

    path('continent_delete/<pk>/', ContinentDeleteView.as_view(), name='continent_delete'),
    path('country_delete/<pk>/', CountryDeleteView.as_view(), name='country_delete'),
    path('city_delete/<pk>/', CityDeleteView.as_view(), name='city_delete'),
    path('hotel_delete/<pk>/', HotelDeleteView.as_view(), name='hotel_delete'),
    path('airport_delete/<pk>/', AirportDeleteView.as_view(), name='airport_delete'),
    path('trip_delete/<pk>/', TripDeleteView.as_view(), name='trip_delete')
]

config/accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(User):
    purchased_trips = []

    class Meta:
        proxy = True

config/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

config/accounts/views.py
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView

from accounts.forms import UserRegisterForm


class SignUpView(SuccessMessageMixin, CreateView):
    template_name = 'sign_up_form.html'
    success_url = reverse_lazy('trip_list')
    form_class = UserRegisterForm
    success_message = "Your profile was created successfully"


class SignInView(LoginView):
    form_class = AuthenticationForm
    template_name = 'sign_in_form.html'
    success_url = 'trip_list'


class UserLogoutView(LogoutView):
    success_url = 'trip_list'

config/accounts/templates/accounts/add_view.html
{% load static %}
{% load core_extras %}

<body>
{% comment %}
<form method="post" class="">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endcomment %}


<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Detail</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
<header id="header">
    <div class="header-top">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-sm-6 col-6 header-top-left">
                    <ul>
                        <li><a href="#">Visit Us</a></li>
                        <li><a href="#">Buy Tickets</a></li>
                    </ul>
                </div>
                <div class="col-lg-6 col-sm-6 col-6 header-top-right">
                    <div class="header-social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container main-menu">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a href="{% url 'trip_list' %}"><img src="{% static 'img/logo.png' %}" alt="" title=""/></a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li><a href="{% url 'trip_list' %}">Home</a></li>
                    <li><a href="{% url 'core:about' %}">About</a></li>
                    <li><a href="{% url 'core:packages' %}">Packages</a></li>
                    <li><a href="{% url 'core:hotels' %}">Hotels</a></li>
                    <li><a href="{% url 'core:insurance' %}">Insurance</a></li>
                    <li class="menu-has-children"><a href="">Blog</a>
                        <ul>
                            <li><a href="{% url 'core:blog_home' %}">Blog Home</a></li>
                            <li><a href="{% url 'core:blog_single' %}">Blog Single</a></li>
                        </ul>
                    </li>
                    <li class="menu-has-children"><a href="">Pages</a>
                        <ul>
                            <li><a href="{% url 'core:elements' %}">Elements</a></li>
                            <li class="menu-has-children"><a href="">Level 2 </a>
                                <ul>
                                    <li><a href="#">Item One</a></li>
                                    <li><a href="#">Item Two</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="{% url 'core:contact' %}">Contact</a></li>
                </ul>
            </nav><!-- #nav-menu-container -->
        </div>
    </div>
</header><!-- #header -->

<!-- start banner Area -->
<section class="about-banner relative" >
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    {{ trip.arrival_city.country }}
                </h1>
                <h2 class="text-white">
                    {{ trip.arrival_city.name }}
                </h2>
<br>
                <p class="text-white link-nav"><a href="{% url 'trip_list' %}">Home </a></p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->

<!-- Start destinations Area -->
<section class="destinations-area section-gap" style="padding: 50px">
    <div class="container" >

        <!-- Start align Area - Form -->
        <div class="whole-wrap">
            <div class="container">
                </div>

                <div class="col-lg-8 col-md-8" style="margin-left: auto; margin-right: auto">
                    <h3 class="mb-30">Formularz</h3>

                            <form method="post" class="">
                                {% csrf_token %}
                                {% for field in form %}
                                <div class="mt-10">
                                    {{ field.errors }}
                                    {{ field.label_tag }} {{ field }}
                                </div>
                                {% endfor %}
                                    <input type="submit" value="Submit" class="genric-btn primary e-large">

                            </form>

                </div>  <!-- Form elements -->
            </div>
        </div>
        <!-- End Align Area -->

    </div>
</section>
<!-- End destinations Area -->



<!-- start footer Area -->
<footer class="footer-area section-gap">
    <div class="container">

        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>About Agency</h6>
                    <p>
                        The world has become so fast paced that people don’t want to stand by reading a page of
                        information, they would much rather look at a presentation and understand the message. It has
                        come to a point
                    </p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Navigation Links</h6>
                    <div class="row">
                        <div class="col">
                            <ul>
                                <li><a href="{% url 'trip_list' %}">Home</a></li>
                                <li><a href="#">Feature</a></li>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Portfolio</a></li>
                            </ul>
                        </div>
                        <div class="col">
                            <ul>
                                <li><a href="#">Team</a></li>
                                <li><a href="#">Pricing</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Newsletter</h6>
                    <p>
                        For business professionals caught between high OEM price and mediocre print and graphic output.
                    </p>
                    <div id="mc_embed_signup">
                        <form target="_blank"
                              action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                              method="get" class="subscription relative">
                            <div class="input-group d-flex flex-row">
                                <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''"
                                       onblur="this.placeholder = 'Email Address '" required="" type="email">
                                <button class="btn bb-btn"><span class="lnr lnr-location"></span></button>
                            </div>
                            <div class="mt-10 info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">InstaFeed</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row footer-bottom d-flex justify-content-between align-items-center">
            <p class="col-lg-8 col-sm-12 footer-text m-0">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                    href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            <div class="col-lg-4 col-sm-12 footer-social">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-dribbble"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
            </div>
        </div>
    </div>
</footer>
<!-- End footer Area -->

<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/easing.min.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/superfish.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/mail-script.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>
</body>

</html>