config/accounts/urls.py
from accounts.views import SignUpView, SignInView, UserLogoutView
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('sign_up/', SignUpView.as_view(), name='sign_up'),
    path('sign_in/', SignInView.as_view(), name='sign_in'),
    path('logout/', UserLogoutView.as_view(), name='logout')

]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import TripListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TripListView.as_view(), name='trip_list'),
    path('core/', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

config/core/urls.py
from core.views import TripDetailsView, template_elements, \
    insurance, ContinentCreateView, CountryCreateView, CityCreateView, AirportCreateView, \
    HotelCreateView, TripCreateView, AdminListView, ContinentDeleteView, AdminContinentDetailView, ContinentUpdateView, \
    AdminTripDetailView, AdminCityDetailView, AdminAirportDetailView, AdminHotelDetailView, AdminCountryDetailView, \
    CountryUpdateView, CityUpdateView, TripUpdateView, AirportUpdateView, HotelUpdateView, CountryDeleteView, \
    HotelDeleteView, AirportDeleteView, TripDeleteView, CityDeleteView, HotelListView, AdditionalServicesView, \
    contact, TripPurchaseCreateView, SearchResultsView, TripPurchaseSummaryView
from django.urls import path
from django.views.decorators.http import require_POST

app_name = 'core'
urlpatterns = [
    path('hotels/', HotelListView.as_view(), name='hotels'),
    path('additional_services/', AdditionalServicesView.as_view(), name='additional_services'),
    path('search_results/', SearchResultsView.as_view(), name='search_results'),

    path('trip_details/<pk>/', TripDetailsView.as_view(), name='trip_details'),
    path('trip_purchase/<pk>/', TripPurchaseCreateView.as_view(), name='trip_purchase'),
    path('trip_purchase_summary/', TripPurchaseSummaryView.as_view(), name='trip_purchase_summary'),

    path('contact/', contact, name='contact'),
    path('elements/', template_elements, name='elements'),
    path('insurance/', insurance, name='insurance'),

    path('add_continent/', ContinentCreateView.as_view(), name='add_continent'),
    path('add_country/', CountryCreateView.as_view(), name='add_country'),
    path('add_city/', CityCreateView.as_view(), name='add_city'),
    path('add_hotel/', HotelCreateView.as_view(), name='add_hotel'),
    path('add_airport/', AirportCreateView.as_view(), name='add_airport'),
    path('add_trip/', TripCreateView.as_view(), name='add_trip'),

    path('admin_list/', AdminListView.as_view(), name='admin_list'),
    path('admin_continent_details/<pk>/', AdminContinentDetailView.as_view(), name='admin_continent_details'),
    path('admin_country_details/<pk>/', AdminCountryDetailView.as_view(), name='admin_country_details'),
    path('admin_city_details/<pk>/', AdminCityDetailView.as_view(), name='admin_city_details'),
    path('admin_hotel_details/<pk>/', AdminHotelDetailView.as_view(), name='admin_hotel_details'),
    path('admin_airport_details/<pk>/', AdminAirportDetailView.as_view(), name='admin_airport_details'),
    path('admin_trip_details/<pk>/', AdminTripDetailView.as_view(), name='admin_trip_details'),

    path('continent_update/<pk>/', ContinentUpdateView.as_view(), name='continent_update'),
    path('country_update/<pk>/', CountryUpdateView.as_view(), name='country_update'),
    path('city_update/<pk>/', CityUpdateView.as_view(), name='city_update'),
    path('hotel_update/<pk>/', HotelUpdateView.as_view(), name='hotel_update'),
    path('airport_update/<pk>/', AirportUpdateView.as_view(), name='airport_update'),
    path('trip_update/<pk>/', TripUpdateView.as_view(), name='trip_update'),

    path('continent_delete/<pk>/', ContinentDeleteView.as_view(), name='continent_delete'),
    path('country_delete/<pk>/', CountryDeleteView.as_view(), name='country_delete'),
    path('city_delete/<pk>/', CityDeleteView.as_view(), name='city_delete'),
    path('hotel_delete/<pk>/', HotelDeleteView.as_view(), name='hotel_delete'),
    path('airport_delete/<pk>/', AirportDeleteView.as_view(), name='airport_delete'),
    path('trip_delete/<pk>/', TripDeleteView.as_view(), name='trip_delete')
]

config/core/forms.py
from django import forms
from core.models import Continent, Country, City, Trip, Airport, Hotel, TripPurchase
from django.contrib.admin.widgets import AdminDateWidget
from django.forms import Textarea, SelectDateWidget

# from accounts.models import Profile
from django.utils.datetime_safe import datetime


class ContinentForm(forms.ModelForm):
    class Meta:
        model = Continent
        fields = (
            'name',
        )
        labels = {
            'name': ('Nazwa')
        }


class CountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = (
            'name', 'continent', 'country_image',
        )
        labels = {
            'name': ('Nazwa'), 'continent': ('Kontynent')
        }


class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = (
            'name', 'country',
        )
        labels = {
            'name': ('Nazwa'), 'country': ('Kraj')
        }


class HotelForm(forms.ModelForm):
    class Meta:
        model = Hotel
        fields = (
            'name', 'stars', 'description', 'city', 'location', 'swimming_pool', 'wifi', 'air_condition',
            'room_service', 'restaurant', 'gym',
        )
        labels = {
            'name': ('Nazwa'), 'stars': ('Liczba gwiazdek'), 'description': ('Opis'), 'city': ('Miasto'),
            'location': ('Lokalizacja'), 'swimming_pool': ('Basen'), 'wifi': ('Wifi'),
            'air_condition': ('Klimatyzacja'),
            'room_service': ('Obsługa hotelowa'), 'restaurant': ('Restauracja'), 'gym': ('Siłownia'),
        }
        help_texts = {
            'location': ('Wstaw link z lokalizacją hotelu z GoogleMaps')
        }


class AirportForm(forms.ModelForm):
    class Meta:
        model = Airport
        fields = (
            'name', 'city'
        )
        labels = {
            'name': ('Nazwa'), 'city': ('Miasto')
        }


class TripForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = (
            'departure_city', 'departure_airport', 'arrival_city', 'arrival_hotel', 'arrival_airport',
            'departure_date',
            'arrival_date', 'return_date', 'back_home_date', 'catering_option', 'price_for_adult',
            'price_for_child',
            'promoted',
        )
        labels = {
            'departure_city': ('Miasto wylotu'), 'departure_airport': ('Lotnisko wylotu'),
            'arrival_city': ('Miasto przylotu'), 'arrival_airport': ('Lotnisko przylotu'),
            'departure_date': ('Data wylotu'), 'arrival_date': ('Data przylotu'), 'return_date': ('Data odlotu'),
            'back_home_date': ('Data powrotu'), 'catering_option': ('Wyżywienie'),
            'price_for_adult': ('Cena za os. dorosłą'), 'price_for_child': ('Cena za dziecko'),
            'promoted': ('Promować?')
        }
        help_texts = {
            'promoted': ('Wycieczka będzie wyświetlana na głównej stronie'),
        }


class TripPurchaseForm(forms.ModelForm):
    class Meta:
        model = TripPurchase
        fields = (
            'trip', 'main_booker', 'adults_number', 'final_price', 'test_char_field'
        )

        labels = {
            'adults_number': ('Liczba osób'),
        }

        widgets = {
            'trip': forms.HiddenInput(), 'main_booker': forms.HiddenInput(), 'final_price': forms.HiddenInput(),
            'test_char_field': forms.HiddenInput(),
        }

    def save(self, commit=True):
        trip_purchased =super().save()
        trip_purchased.save()
        return trip_purchased

config/core/views.py
import datetime

# from accounts.models import Profile
from core.forms import ContinentForm, CountryForm, CityForm, HotelForm, AirportForm, TripForm, TripPurchaseForm
from core.models import Trip, Country, Continent, City, Hotel, Airport, Comment, TripPurchase
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.db.models import Q, Max
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.timezone import now
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from search_views.filters import BaseFilter
from search_views.views import SearchListView


def template_elements(request):
    return render(request, 'core/elements.html')


def about(request):
    return render(request, 'core/about.html')


def blog_home(request):
    return render(request, 'core/blog-home.html')


def blog_single(request):
    return render(request, 'core/blog-single.html')


def contact(request):
    return render(request, 'core/contact.html')


def insurance(request):
    return render(request, 'core/insurance.html')


class TripDetailsView(DetailView):
    model = Trip
    template_name = 'core/trip_details.html'

    def get_context_data(self, **kwargs):
        context = super(TripDetailsView, self).get_context_data(**kwargs)
        context['form'] = TripPurchaseForm

        # todo: zapytanie które wyświetla najniższą cenę na stronie głównej
        # trips = Trip.objects.filter(country=self.kwargs['pk'])
        # context['lowest_price'] = trips.order_by('-price_for_adult').first()

        return context


class TripPurchaseCreateView(LoginRequiredMixin, CreateView):
    login_url = 'accounts:sign_in'
    form_class = TripPurchaseForm
    template_name = 'trip_purchase_form.html'
    success_url = reverse_lazy('core:trip_purchase_summary')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trip'] = Trip.objects.get(pk=self.kwargs.get('pk'))
        return context

    def get_initial(self):
        initial = super().get_initial()
        initial['trip'] = self.kwargs.get('pk')
        initial['main_booker'] = self.request.user.id
        initial['adults_number'] = 0
        initial['kids_number'] = 0

        trip = Trip.objects.get(pk=self.kwargs.get('pk'))
        initial['final_price'] = trip.price_for_adult

        initial['test_char_field'] = trip.price_for_adult * initial['adults_number']

        return initial


class TripPurchaseSummaryView(LoginRequiredMixin, ListView):
    model = TripPurchase
    template_name = 'core/trip_purchase_summary.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['trips_purchased'] = TripPurchase.objects.all()
        this_users_trip = TripPurchase.objects.filter(main_booker_id=self.request.user.id)
        context['this_trip_id'] = this_users_trip.aggregate(Max('id'))
        context['this_trip'] = this_users_trip.order_by('-id').first()

        this_trip = this_users_trip.order_by('-id').first()
        context['final_price'] = (this_trip.final_price * this_trip.adults_number)

        return context


class TripCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'core.add_trip'
    title = 'Add trip'
    template_name = 'form.html'
    form_class = TripForm
    success_url = reverse_lazy('core:admin_list')

    def get_initial(self):
        initial = super().get_initial()
        initial['departure_city'] = 3
        initial['price_for_adult'] = 12345
        initial['promoted'] = True
        return initial


class ContinentCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'core.add_continent'
    title = 'Add continent'
    template_name = 'form.html'
    form_class = ContinentForm
    success_url = reverse_lazy('core:admin_list')


class TripListView(ListView):
    model = Trip
    template_name = 'core/index.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TripListView, self).get_context_data(**kwargs)
        context['all_trips'] = Trip.objects.filter(departure_date__lt=now())
        context['promoted_trips'] = Trip.objects.filter(promoted=True).filter(departure_date__gt=now())[:3]
        context['last_minute_trips'] = Trip.objects.filter(departure_date__lt=(now() + datetime.timedelta(30)))[:3]
        context['all_countries'] = Country.objects.exclude(name='Polska')
        context['all_comments'] = Comment.objects.all()
        context['today'] = datetime.datetime.now()
        # context['prices'] = [i.price_for_adult for i in Trip.objects.all() if i.arrival_city.country.name=="Hiszpania"]
        return context


class HotelListView(ListView):
    model = Hotel
    template_name = 'core/hotels.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(HotelListView, self).get_context_data()
        context['hotels'] = Hotel.objects.order_by('-stars')
        return context


class AdditionalServicesView(ListView):
    model = Comment
    template_name = 'core/additional_services.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['all_comments'] = Comment.objects.all()
        return context


class AdminListView(PermissionRequiredMixin, ListView):
    permission_required = 'core.view_trip'
    model = Trip
    template_name = 'core/admin_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(AdminListView, self).get_context_data(**kwargs)
        context['continents'] = Continent.objects.all()
        context['countries'] = Country.objects.all()
        context['cities'] = City.objects.all()
        context['hotels'] = Hotel.objects.all()
        context['airports'] = Airport.objects.all()
        context['trips'] = Trip.objects.all()
        return context


class CountryCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'core.add_country'
    title = 'Add country'
    template_name = 'form.html'
    form_class = CountryForm
    success_url = reverse_lazy('core:admin_list')


class CityCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'core.add_city'
    title = 'Add city'
    template_name = 'form.html'
    form_class = CityForm
    success_url = reverse_lazy('core:admin_list')


class HotelCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'core.add_hotel'
    title = 'Add hotel'
    template_name = 'form.html'
    form_class = HotelForm
    success_url = reverse_lazy('core:admin_list')


class AirportCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'core.add_airport'
    title = 'Add airport'
    template_name = 'form.html'
    form_class = AirportForm
    success_url = reverse_lazy('core:admin_list')


class AdminContinentDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'core.view_continent'
    model = Continent
    template_name = 'core/admin_continent_details.html'


class ContinentUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'core.change_continent'
    model = Continent
    template_name = 'edit_form.html'
    form_class = ContinentForm
    success_url = reverse_lazy('core:admin_list')


class ContinentDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'core.delete_continent'
    model = Continent
    template_name = 'delete_form.html'
    form_class = ContinentForm
    success_url = reverse_lazy('core:admin_list')


class AdminCountryDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'core.view_country'
    model = Country
    template_name = 'core/admin_country_details.html'


class CountryUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'core.change_country'
    model = Country
    template_name = 'edit_form.html'
    form_class = CountryForm
    success_url = reverse_lazy('core:admin_list')


class CountryDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'core.delete_country'
    model = Country
    template_name = 'delete_form.html'
    form_class = CountryForm
    success_url = reverse_lazy('core:admin_list')


class AdminCityDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'core.view_city'
    model = City
    template_name = 'core/admin_city_details.html'


class CityUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'core.change_city'
    model = City
    template_name = 'edit_form.html'
    form_class = CityForm
    success_url = reverse_lazy('core:admin_list')


class CityDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'core.delete_city'
    model = City
    template_name = 'delete_form.html'
    form_class = CityForm
    success_url = reverse_lazy('core:admin_list')


class AdminHotelDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'core.view_hotel'
    model = Hotel
    template_name = 'core/admin_hotel_details.html'


class HotelUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'core.change_hotel'

    model = Hotel
    template_name = 'edit_form.html'
    form_class = HotelForm
    success_url = reverse_lazy('core:admin_list')


class HotelDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'core.delete_hotel'
    model = Hotel
    template_name = 'delete_form.html'
    form_class = HotelForm
    success_url = reverse_lazy('core:admin_list')


class AdminAirportDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'core.view_airport'
    model = Airport
    template_name = 'core/admin_airport_details.html'


class AirportUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'core.change_airport'

config/core/templates/core/admin_airport_details.html
{% load static %}
{% load core_extras %}

<body>
{% comment %}
<form method="post" class="">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endcomment %}


<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Detail</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
<header id="header">
    <div class="header-top">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-sm-6 col-6 header-top-left">
                    <ul>
                        <li><a target="_blank" href="https://www.google.com/maps/place/Gda%C5%84sk/@54.3612063,18.5499451,11z/data=!3m1!4b1!4m5!3m4!1s0x46fd731c14d4fa6f:0x9bb9fbf163b7be8d!8m2!3d54.3520252!4d18.6466384" >
                            Odwiedź nas</a></li>
                        <li><a target="_blank" href="https://www.skyscanner.pl/">Kup bilety</a></li>
                    </ul>
                </div>
                <div class="col-lg-6 col-sm-6 col-6 header-top-right">
                    <div class="header-social">
                        <a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook"></i></a>
                        <a href="https://www.twitter.com/" target="_blank"><i class="fa fa-twitter"></i></a>
                        <a href="https://www.instagram.com/" target="_blank"><i class="fa fa-instagram"></i></a>
                        <a href="https://www.snapchat.com/" target="_blank"><i class="fa fa-snapchat"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container main-menu">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a href="{% url 'trip_list' %}"><img src="{% static 'img/logo.png' %}" alt="" title=""/></a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li><a href="{% url 'trip_list' %}">Home</a></li>
                    <li><a href="{% url 'core:additional_services' %}">Dodatkowe usługi</a></li>
                    <li><a href="{% url 'core:hotels' %}">Hotele</a></li>
                    <li><a href="{% url 'core:contact' %}">Kontakt</a></li>

                    {% if user|is_group:'staff' %}
                    <li><a href="{% url 'core:admin_list' %}">Panel admina</a></li>
                    {% endif %}

                    {% if user.is_authenticated %}
                    <li class="menu-has-children"><a href=#>Witaj, {{ user }}!</a>
                        <ul>
                            <li><a href="{% url 'accounts:logout' %}">Wyloguj</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="menu-has-children"><a href=#>Logowanie</a>
                        <ul>
                            <li><a href="{% url 'accounts:sign_in' %}">Zaloguj</a></li>
                            <li><a href="{% url 'accounts:sign_up' %}">Zarejestruj</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
            </nav><!-- #nav-menu-container -->
        </div>
    </div>
</header><!-- #header -->

<!-- start banner Area -->
<section class="about-banner relative" >
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    {{ trip.arrival_city.country }}
                </h1>
                <h2 class="text-white">
                    {{ trip.arrival_city.name }}
                </h2>
<br>
                <p class="text-white link-nav"><a href="{% url 'trip_list' %}">Home </a></p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->

<!-- Start destinations Area -->
<section class="destinations-area section-gap" style="padding: 50px">
    <div class="container" >

        <!-- Start align Area - Form -->
        <div class="whole-wrap">
            <div class="container">
                </div>

            <div class="col-lg-4 col-md-6 banner-right">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link genric-btn info" id="continent-tab" data-toggle="tab" href="#continent" role="tab"
                           aria-controls="continent" aria-selected="true">Kontynenty</a>
                    </li>
                </ul>
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="continent" role="tabpanel" aria-labelledby="continent-tab">
                        <div class="form-wrap">
                            <un>
                                <li>{{ airport.id }}</li>
                                <li>{{ airport.name }}</li>

                                <li> <a href="{% url 'core:admin_list' %}" class="genric-btn info">Wróć</a>
                                    <a href="{% url 'core:airport_update' pk=airport.id %}" class="genric-btn warning">Edytuj</a>
                                <a href="{% url 'core:airport_delete' pk=airport.id %}" class="genric-btn danger">Usuń</a></li>
                            </un>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="hotel" role="tabpanel" aria-labelledby="hotel-tab">
                        <form class="form-wrap">
                            <input type="text" class="form-control" name="name" placeholder="From "
                                   onfocus="this.placeholder = ''" onblur="this.placeholder = 'From '">
                            <input type="text" class="form-control" name="to" placeholder="To "
                                   onfocus="this.placeholder = ''" onblur="this.placeholder = 'To '">
                            <input type="text" class="form-control date-picker" name="start" placeholder="Start "
                                   onfocus="this.placeholder = ''" onblur="this.placeholder = 'Start '">
                            <input type="text" class="form-control date-picker" name="return" placeholder="Return "
                                   onfocus="this.placeholder = ''" onblur="this.placeholder = 'Return '">
                            <input type="number" min="1" max="20" class="form-control" name="adults"
                                   placeholder="Adults " onfocus="this.placeholder = ''"
                                   onblur="this.placeholder = 'Adults '">
                            <input type="number" min="1" max="20" class="form-control" name="child" placeholder="Child "
                                   onfocus="this.placeholder = ''" onblur="this.placeholder = 'Child '">
                            <a href="#" class="primary-btn text-uppercase">Search Hotels</a>
                        </form>
                    </div>
                    <div class="tab-pane fade" id="holiday" role="tabpanel" aria-labelledby="holiday-tab">
                        <form class="form-wrap">
                            <input type="text" class="form-control" name="name" placeholder="From "
                                   onfocus="this.placeholder = ''" onblur="this.placeholder = 'From '">
                            <input type="text" class="form-control" name="to" placeholder="To "
                                   onfocus="this.placeholder = ''" onblur="this.placeholder = 'To '">
                            <input type="text" class="form-control date-picker" name="start" placeholder="Start "
                                   onfocus="this.placeholder = ''" onblur="this.placeholder = 'Start '">
                            <input type="text" class="form-control date-picker" name="return" placeholder="Return "
                                   onfocus="this.placeholder = ''" onblur="this.placeholder = 'Return '">
                            <input type="number" min="1" max="20" class="form-control" name="adults"
                                   placeholder="Adults " onfocus="this.placeholder = ''"
                                   onblur="this.placeholder = 'Adults '">
                            <input type="number" min="1" max="20" class="form-control" name="child" placeholder="Child "
                                   onfocus="this.placeholder = ''" onblur="this.placeholder = 'Child '">
                            <a href="#" class="primary-btn text-uppercase">Search Holidays</a>
                        </form>
                    </div>
                </div>
            </div>


            </div>
        </div>
        <!-- End Align Area -->

    </div>
</section>
<!-- End destinations Area -->



<!-- start footer Area -->
<footer class="footer-area section-gap" style="padding: 0px 0px 40px 0px">
    <div class="container">
        <div class="row footer-bottom d-flex justify-content-between align-items-center">
            <p class="col-lg-8 col-sm-12 footer-text m-0">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                    href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            <div class="col-lg-4 col-sm-12 footer-social">
                <a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook"></i></a>
                <a href="https://www.twitter.com/" target="_blank"><i class="fa fa-twitter"></i></a>
                <a href="https://www.instagram.com/" target="_blank"><i class="fa fa-instagram"></i></a>
                <a href="https://www.snapchat.com/" target="_blank"><i class="fa fa-snapchat"></i></a>
            </div>
        </div>
    </div>
</footer>
<!-- End footer Area -->

<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/easing.min.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/superfish.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/mail-script.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>
</body>

</html>